require 'custom.configs.colorizer'
require 'custom.configs.scroll'
require 'custom.configs.harpoon'
require 'custom.configs.snippets'
require 'custom.configs.split'
require 'custom.configs.floatborder'
require 'custom.configs.treesitter'
