-- Trying this as a keymap instead
-- An idea to modify the find_files default to show hidden files
-- local telescope = require('telescope')
-- telescope.setup({
-- 	pickers = {
-- 		find_files = {
-- 			hidden = true,
-- 		}
-- 	}
-- })
